export const vehicles = [
  {
    slug: 'territory',
    brand: 'Ford',
    model: 'Ford Territory',
    year: 2026,
    price: '$599,000 - $798,500',
    description:
      'Disfruta de viajes seguros y placenteros con tu familia gracias al amplio espacio y moderno diseño de Ford Territory 2026.',
    features: [
      'Tecnología y rendimiento en una SUV',
      'Amplio espacio interior',
      'Diseño moderno',
      'Gran tecnología integrada',
      'Seguridad avanzada',
      'Confort para toda la familia',
    ],
    specs: {
      motor: '1.8L EcoBoost',
      potencia: '190 HP',
      transmision: 'Automática',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
  {
    slug: 'mazda2',
    brand: 'Mazda',
    model: 'Mazda 2',
    year: 2025,
    price: '$301,900 - $398,900',
    description:
      'El Mazda 2 combina diseño elegante con tecnología avanzada, cámara de visión trasera y monitoreo de presión de llantas.',
    features: [
      'Faros LED con encendido automático',
      'Rines de aluminio de 16 pulgadas',
      'TPMS',
      'Cámara de visión trasera',
      'Diseño elegante',
      'Tecnología avanzada',
    ],
    specs: {
      motor: '1.5L Skyactiv',
      potencia: '110 HP',
      transmision: 'Automática 6 vel',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
  {
    slug: 'p-22',
    brand: 'DFAC',
    model: 'DFAC P22',
    year: 2025,
    price: '$467,900 - $517,900',
    description:
      'Una nueva generación de líderes. Robustez y eficiencia para el trabajo diario con potencia y capacidad de carga.',
    features: [
      'Robustez y eficiencia',
      'Gran capacidad de carga',
      'Potencia confiable',
      'Diseño funcional',
      'Ideal para trabajo',
      'Durabilidad garantizada',
    ],
    specs: {
      motor: '2.0L Turbo Diesel',
      potencia: '140 HP',
      transmision: 'Manual 6 vel',
      combustible: 'Diésel',
      traccion: '4x2',
    },
  },
  {
    slug: 'ram-700',
    brand: 'Ram',
    model: 'Ram 700',
    year: 2025,
    price: '$339,900 - $517,900',
    description:
      'Excelente capacidad para cualquier tipo de trabajo con equipamiento interior y exterior destacado.',
    features: [
      'Capacidad de carga superior',
      'Equipamiento exclusivo',
      'Diseño robusto',
      'Versatilidad total',
      'Confort interior',
      'Tecnología conectada',
    ],
    specs: {
      motor: '1.4L Tigershark',
      potencia: '85 HP',
      transmision: 'Manual 5 vel',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
  {
    slug: 'peugeot-2009',
    brand: 'Peugeot',
    model: 'Peugeot 2008',
    year: 2025,
    price: '$463,900 - $545,900',
    description:
      'La SUV Peugeot 2008 redefine los códigos estéticos del segmento con estilo contundente y motor turbo.',
    features: [
      'Luces LED delanteras y traseras',
      'Parrilla amplia con escudo Peugeot',
      'Rines de aluminio de 17 pulgadas',
      'Motor turbo',
      'SUV compacta moderna',
      'Diseño contundente',
    ],
    specs: {
      motor: '1.2L Turbo',
      potencia: '130 HP',
      transmision: 'Automática 6 vel',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
  {
    slug: 'pulse-fiat',
    brand: 'Fiat',
    model: 'Fiat Pulse',
    year: 2025,
    price: '$355,900 - $432,900',
    description:
      'SUV de Fiat con auténtico diseño italiano, dinámico y moderno.',
    features: [
      'Diseño italiano auténtico',
      'Dinámico y moderno',
      'Tecnología conectada',
      'Estilo único',
      'Versatilidad urbana',
      'Confort superior',
    ],
    specs: {
      motor: '1.3L Firefly',
      potencia: '101 HP',
      transmision: 'CVT',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
  {
    slug: 'navigator',
    brand: 'Lincoln',
    model: 'Lincoln Navigator',
    year: 2025,
    price: '$2,599,900 - $3,079,900',
    description:
      'Lincoln Navigator redefine el lujo con diseño audaz, pantalla panorámica y experiencia digital Lincoln.',
    features: [
      'Pantalla panorámica 48 pulgadas',
      'Lincoln Digital Experience',
      'Lincoln Rejuvenate',
      'Asientos de piel premium',
      'Sistema Revel Ultima 3D',
      'Lincoln Co-Pilot360',
    ],
    specs: {
      motor: '3.5L V6 Biturbo',
      potencia: '450 HP',
      transmision: 'Automática 10 vel',
      combustible: 'Gasolina',
      traccion: '4x4',
    },
  },
  {
    slug: 'x-70',
    brand: 'Jetour',
    model: 'Jetour X70',
    year: 2025,
    price: '$439,900',
    description:
      'SUV con alto factor de seguridad, motor con garantía prolongada y suspensión independiente multibrazo.',
    features: [
      'EPB + AUTOHOLD',
      'Motor con garantía prolongada',
      'Suspensión independiente multibrazo',
      'Barra estabilizadora',
      'Alta seguridad',
      'Estabilidad de conducción',
    ],
    specs: {
      motor: '1.5L Turbo',
      potencia: '156 HP',
      transmision: 'Automática 6 vel',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
  {
    slug: 'attitude',
    brand: 'Dodge',
    model: 'Dodge Attitude',
    year: 2025,
    price: '$398,900',
    description:
      'Dodge Attitude R/T con diseño frontal imponente, líneas robustas y carácter deportivo.',
    features: [
      'Diseño deportivo R/T',
      'Líneas agresivas',
      'Contornos dinámicos',
      'Imponente diseño frontal',
      'Carácter robusto',
      'Potencia atractiva',
    ],
    specs: {
      motor: '1.2L Turbo',
      potencia: '116 HP',
      transmision: 'CVT',
      combustible: 'Gasolina',
      traccion: 'Delantera',
    },
  },
]

export const dealerships = [
  { brandName: 'ford', displayName: 'Ford', city: 'Culiacán', phone: '6675032395', whatsapp: '526675032395' },
  { brandName: 'ford', displayName: 'Ford', city: 'Ciudad Obregón', phone: '6442222834', whatsapp: '526442222834' },
  { brandName: 'ford', displayName: 'Ford', city: 'Los Mochis', phone: '6682533839', whatsapp: '526682533839' },
  { brandName: 'mazda', displayName: 'Mazda', city: 'Los Cabos', phone: '6241840641', whatsapp: '526241840641' },
  { brandName: 'mazda', displayName: 'Mazda', city: 'Culiacán', phone: '6674672828', whatsapp: '526674672828' },
  { brandName: 'mazda', displayName: 'Mazda', city: 'Mazatlán', phone: '6699184897', whatsapp: '526699184897' },
  { brandName: 'lincoln', displayName: 'Lincoln', city: 'Culiacán', phone: '6673038502', whatsapp: '526673038502' },
  { brandName: 'dongfeng', displayName: 'Dongfeng', city: 'Culiacán', phone: '6673038702', whatsapp: '526673038702' },
  { brandName: 'dongfeng', displayName: 'Dongfeng', city: 'Ciudad Obregón', phone: '6442220969', whatsapp: '526442220969' },
  { brandName: 'dongfeng', displayName: 'Dongfeng', city: 'Hermosillo', phone: '6621233933', whatsapp: '526621233933' },
  { brandName: 'dongfeng', displayName: 'Dongfeng', city: 'Guadalajara', phone: '3322567752', whatsapp: '523322567752' },
  { brandName: 'stellantis', displayName: 'Stellantis', city: 'Ciudad Obregón', phone: '6442220568', whatsapp: '526442220568' },
  { brandName: 'jetour', displayName: 'Jetour', city: 'Culiacán', phone: '6671025850', whatsapp: '526671025850' },
  { brandName: 'jetour', displayName: 'Jetour', city: 'Ciudad Obregón', phone: '6442044858', whatsapp: '526442044858' },
  { brandName: 'seminuevos', displayName: 'Seminuevos GB Culiacan', city: 'Culiacan', phone: '6442364338', whatsapp: '526442364338' },
  { brandName: 'seminuevos', displayName: 'Seminuevos GB Mazatlan', city: 'Mazatlan', phone: '6442364338', whatsapp: '526442364338' },
  { brandName: 'seminuevos', displayName: 'Seminuevos GB Guasave', city: 'Guasave', phone: '6442364338', whatsapp: '526442364338' },
  { brandName: 'seminuevos', displayName: 'Seminuevos GB Los Mochis', city: 'Los Mochis', phone: '6442364338', whatsapp: '526442364338' },
]
