/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    vehicles: Vehicle;
    'vehicle-tags': VehicleTag;
    'vehicle-collections': VehicleCollection;
    'import-jobs': ImportJob;
    'vehicle-media-assets': VehicleMediaAsset;
    'vehicle-image-searches': VehicleImageSearch;
    'workshop-jobs': WorkshopJob;
    'image-templates': ImageTemplate;
    pages: Page;
    media: Media;
    leads: Lead;
    'analytics-events': AnalyticsEvent;
    dealerships: Dealership;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    'vehicle-tags': VehicleTagsSelect<false> | VehicleTagsSelect<true>;
    'vehicle-collections': VehicleCollectionsSelect<false> | VehicleCollectionsSelect<true>;
    'import-jobs': ImportJobsSelect<false> | ImportJobsSelect<true>;
    'vehicle-media-assets': VehicleMediaAssetsSelect<false> | VehicleMediaAssetsSelect<true>;
    'vehicle-image-searches': VehicleImageSearchesSelect<false> | VehicleImageSearchesSelect<true>;
    'workshop-jobs': WorkshopJobsSelect<false> | WorkshopJobsSelect<true>;
    'image-templates': ImageTemplatesSelect<false> | ImageTemplatesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    dealerships: DealershipsSelect<false> | DealershipsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: null;
  widgets: {
    'operations-dashboard': OperationsDashboardWidget;
    'analytics-dashboard': AnalyticsDashboardWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  uuid?: string | null;
  /**
   * Se genera al guardar con marca, modelo, año y UUID del vehículo.
   */
  slug: string;
  brand: string;
  modelFamily?: string | null;
  model: string;
  trim?: string | null;
  /**
   * Requerido para publicar. Opcional al importar borradores.
   */
  year?: number | null;
  exteriorColor?: string | null;
  interiorColor?: string | null;
  /**
   * Mapeado desde DES_TIPO_VEHICULO en importaciones.
   */
  vehicleType?: string | null;
  /**
   * Mapeado desde DES_SEGMENTO en importaciones.
   */
  segment?: string | null;
  /**
   * Mapeado desde DES_TIPO_MOTOR en importaciones.
   */
  motorType?: string | null;
  /**
   * Referencia visible para ventas y WhatsApp. Si se deja vacio se usara el UUID corto.
   */
  stockId?: string | null;
  condition: 'new' | 'used';
  /**
   * Define a que agencia pertenece esta unidad y a que WhatsApp se enviaran los leads. Requerida para publicar salvo fallback explicito.
   */
  dealership?: (number | null) | Dealership;
  /**
   * Opcional. Si se deja vacia, la pagina usara la ciudad de la agencia seleccionada.
   */
  city?: string | null;
  mileage?: number | null;
  bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
  transmission?: ('automatic' | 'manual' | 'cvt') | null;
  fuel?: ('gasoline' | 'diesel' | 'hybrid' | 'electric') | null;
  /**
   * Crea etiquetas como Un dueno, Garantia, Factura agencia, Promo o Recien llegado.
   */
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Etiquetas reutilizables para colecciones, filtros y tarjetas publicas.
   */
  tags?: (number | VehicleTag)[] | null;
  /**
   * Marca esta unidad para bloques editoriales o colecciones inteligentes.
   */
  featured?: boolean | null;
  /**
   * Requerido para publicar. Opcional al importar. Escribe un número o rango; se guardará como MXN.
   */
  price?: string | null;
  inventoryStatus: 'available' | 'reserved' | 'sold';
  publishStatus?: ('draft' | 'needs_review' | 'published' | 'archived') | null;
  /**
   * Permite publicar usando el WhatsApp global si todavia no hay agencia exacta. Usar solo como excepcion operativa.
   */
  allowFallbackRouting?: boolean | null;
  /**
   * Se calcula automáticamente salvo aprobaciones/rechazos manuales.
   */
  imageStatus?: ('missing' | 'candidate_found' | 'uploaded' | 'generated' | 'approved' | 'rejected') | null;
  specStatus?: ('missing' | 'partial' | 'matched' | 'manual' | 'verified') | null;
  /**
   * Calculado automáticamente al guardar.
   */
  completenessScore?: number | null;
  publishedAt?: string | null;
  lastPublishedBy?: (number | null) | User;
  lastReviewedAt?: string | null;
  lastReviewedBy?: (number | null) | User;
  reviewNotes?: string | null;
  /**
   * Identificador del inventario de origen para detectar duplicados.
   */
  sourceId?: string | null;
  sourceImportId?: string | null;
  /**
   * Nombre de agencia tal como vino en el archivo importado.
   */
  sourceDealerName?: string | null;
  imageUrl?: string | null;
  imagePath?: string | null;
  imageFilename?: string | null;
  image?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  specs?: {
    tipo?: string | null;
    motor?: string | null;
    potencia?: string | null;
    transmision?: string | null;
    combustible?: string | null;
    traccion?: string | null;
    cylinders?: string | null;
    seats?: string | null;
    doors?: string | null;
    lengthMm?: string | null;
    widthMm?: string | null;
    heightMm?: string | null;
    wheelbaseMm?: string | null;
    maxTrunkCapacityL?: string | null;
    torqueNm?: string | null;
    fuelTankCapacityL?: string | null;
  };
  /**
   * Datos técnicos normalizados desde catálogo interno o RapidAPI.
   */
  sourceMeta?: {
    specSource?: ('catalog' | 'rapidapi' | 'manual' | 'none') | null;
    externalMakeId?: string | null;
    externalModelId?: string | null;
    externalGenerationId?: string | null;
    externalTrimId?: string | null;
    lastSpecSyncAt?: string | null;
  };
  /**
   * Datos importados desde CSV que no pertenecen al esquema principal.
   */
  customFields?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Agrega secciones simples debajo de la página del vehículo: imagen y texto, galerías, beneficios o CTA.
   */
  landing?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            body?: string | null;
            items?:
              | {
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlightList';
          }
        | {
            heading: string;
            items?:
              | {
                  feature: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Controla secciones fijas de la página de detalle para este vehículo.
   */
  templateOverrides?: {
    gallery?: ('inherit' | 'show' | 'hide') | null;
    purchaseCard?: ('inherit' | 'show' | 'hide') | null;
    quickSpecs?: ('inherit' | 'show' | 'hide') | null;
    description?: ('inherit' | 'show' | 'hide') | null;
    features?: ('inherit' | 'show' | 'hide') | null;
    similarVehicles?: ('inherit' | 'show' | 'hide') | null;
    mobileCta?: ('inherit' | 'show' | 'hide') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealerships".
 */
export interface Dealership {
  id: number;
  /**
   * Usa el grupo comercial para enrutar WhatsApp: ford, mazda, lincoln, stellantis, dongfeng o jetour.
   */
  brandName: string;
  displayName: string;
  city: string;
  state?: string | null;
  address?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  hours?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Se usa si no hay una agencia exacta para la marca seleccionada.
   */
  defaultForCity?: boolean | null;
  salesRepName?: string | null;
  internalNotes?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-tags".
 */
export interface VehicleTag {
  id: number;
  name: string;
  slug: string;
  label?: string | null;
  description?: string | null;
  type?: ('manual' | 'automatic' | 'system') | null;
  color?: string | null;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Define qué acciones puede realizar el usuario en el CMS.
   */
  role?: ('admin' | 'inventory_manager' | 'content_editor' | 'sales_manager' | 'media_editor' | 'viewer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-collections".
 */
export interface VehicleCollection {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  collectionType: 'manual' | 'smart';
  manualVehicles?: (number | Vehicle)[] | null;
  rules?: {
    condition?: ('new' | 'used') | null;
    brand?: string | null;
    city?: string | null;
    dealership?: (number | null) | Dealership;
    bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
    segment?: string | null;
    vehicleType?: string | null;
    fuel?: ('gasoline' | 'diesel' | 'hybrid' | 'electric') | null;
    transmission?: ('automatic' | 'manual' | 'cvt') | null;
    tags?: (number | VehicleTag)[] | null;
    inventoryStatus?: ('available' | 'reserved' | 'sold') | null;
    publishStatus?: ('draft' | 'needs_review' | 'published' | 'archived') | null;
  };
  sort?:
    | ('newest' | 'mostViewed' | 'mostClicked' | 'mostLeads' | 'priceAsc' | 'priceDesc' | 'mileageAsc' | 'yearDesc')
    | null;
  limit?: number | null;
  isVisible?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs".
 */
export interface ImportJob {
  id: number;
  fileName: string;
  fileType?: ('csv' | 'xlsx') | null;
  status?: ('pending' | 'validating' | 'ready' | 'importing' | 'completed' | 'rolled_back' | 'failed') | null;
  rowCount?: number | null;
  createdCount?: number | null;
  updatedCount?: number | null;
  skippedCount?: number | null;
  reviewCount?: number | null;
  errorCount?: number | null;
  /**
   * Mapa de columna de archivo -> campo del CMS.
   */
  mapping?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summary?: string | null;
  errors?:
    | {
        row?: number | null;
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Usado para revisar o revertir esta importación.
   */
  createdVehicleIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-media-assets".
 */
export interface VehicleMediaAsset {
  id: number;
  /**
   * Etiqueta interna para identificar la imagen.
   */
  title?: string | null;
  vehicle?: (number | null) | Vehicle;
  media: number | Media;
  sourceType?: ('uploaded' | 'dealer_photo' | 'api_candidate' | 'ai_generated' | 'ai_edited' | 'representative') | null;
  sourceUrl?: string | null;
  sourceProvider?: string | null;
  /**
   * brand + model + year + trim + exteriorColor normalizados.
   */
  matchKey?: string | null;
  make?: string | null;
  model?: string | null;
  year?: number | null;
  trim?: string | null;
  exteriorColor?: string | null;
  approvalStatus?: ('draft' | 'needs_review' | 'approved' | 'rejected') | null;
  matchConfidence?:
    | (
        | 'exact_vehicle'
        | 'same_trim_color'
        | 'same_model_color'
        | 'same_model'
        | 'representative'
        | 'generated'
        | 'unknown'
      )
    | null;
  exteriorColorMatched?: boolean | null;
  rightsStatus?: ('owned' | 'licensed' | 'unknown') | null;
  usage?: ('vehicle_hero' | 'vehicle_gallery' | 'homepage' | 'landing_page' | 'promo_banner' | 'social_ad') | null;
  notes?: string | null;
  createdBy?: (number | null) | User;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-image-searches".
 */
export interface VehicleImageSearch {
  id: number;
  provider: string;
  matchKey: string;
  query?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  candidates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fetchedAt?: string | null;
  expiresAt?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-jobs".
 */
export interface WorkshopJob {
  id: number;
  title?: string | null;
  jobType?: ('vehicle_image' | 'marketing_asset') | null;
  linkedVehicle?: (number | null) | Vehicle;
  inputImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  promptPreset?:
    | (
        | 'vehicle_hero'
        | 'transparent_bg'
        | 'clean_dealership_bg'
        | 'logo_overlay'
        | 'homepage_banner'
        | 'social_ad'
        | 'promo_banner'
        | 'seminuevo_gallery_cover'
        | 'new_car_representative'
      )
    | null;
  aspectRatio?: ('16:9' | '1:1' | '9:16' | '4:3') | null;
  prompt?: string | null;
  styleTemplate?: (number | null) | ImageTemplate;
  styleName?: string | null;
  stylePrompt?: string | null;
  messages?:
    | {
        role: 'user' | 'assistant' | 'system';
        content: string;
        turnId?: string | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Se completa automáticamente desde el vehículo enlazado.
   */
  vehicleContext?: {
    brand?: string | null;
    model?: string | null;
    year?: number | null;
    color?: string | null;
  };
  styleReferenceUrl?: string | null;
  outputs?:
    | {
        image?: (number | null) | Media;
        url?: string | null;
        turnId?: string | null;
        selected?: boolean | null;
        id?: string | null;
      }[]
    | null;
  approvedOutput?: (number | null) | Media;
  saveDestination?:
    | (
        | 'media_library'
        | 'vehicle_hero'
        | 'vehicle_gallery'
        | 'vehicle_listing_section'
        | 'homepage_section'
        | 'landing_section'
        | 'promo_banner'
      )
    | null;
  status?: ('draft' | 'generating' | 'ready_for_review' | 'approved' | 'rejected' | 'failed') | null;
  error?: string | null;
  createdBy?: (number | null) | User;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-templates".
 */
export interface ImageTemplate {
  id: number;
  name: string;
  preset?:
    | (
        | 'vehicle_hero'
        | 'transparent_bg'
        | 'clean_dealership_bg'
        | 'logo_overlay'
        | 'homepage_banner'
        | 'social_ad'
        | 'promo_banner'
        | 'seminuevo_gallery_cover'
        | 'new_car_representative'
      )
    | null;
  prompt?: string | null;
  referenceImage?: (number | null) | Media;
  description?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * No uses rutas reservadas como cars, seminuevos, marcas o api.
   */
  slug: string;
  status?: ('draft' | 'published' | 'archived') | null;
  isVisible?: boolean | null;
  showInNavigation?: boolean | null;
  navLabel?: string | null;
  navParent?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  sections: (
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        media?: (number | null) | Media;
        videoUrl?: string | null;
        primaryLink: {
          label: string;
          href: string;
        };
        secondaryLink: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        items?:
          | {
              image: number | Media;
              alt?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promoStrip';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        limit?: number | null;
        source?: ('latestUsed' | 'manual' | 'city' | 'brand' | 'bodyType') | null;
        city?: string | null;
        brand?: string | null;
        bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
        display?: {
          showPrice?: boolean | null;
          showMileage?: boolean | null;
          showCity?: boolean | null;
          showSpecs?: boolean | null;
        };
        vehicles?: (number | Vehicle)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuredVehicles';
      }
    | {
        collection: number | VehicleCollection;
        heading?: string | null;
        body?: string | null;
        layout?: ('grid' | 'carousel' | 'featuredSplit') | null;
        limit?: number | null;
        display?: {
          showPrice?: boolean | null;
          showMileage?: boolean | null;
          showCity?: boolean | null;
          showTags?: boolean | null;
        };
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'inventoryCollection';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        media?: (number | null) | Media;
        limit?: number | null;
        city?: string | null;
        brand?: string | null;
        bodyType?: ('' | 'sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'inventorySearch';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        layout?: ('cards' | 'compact' | 'map') | null;
        limit?: number | null;
        cities?:
          | {
              city?: string | null;
              label?: string | null;
              href?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cityInventory';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        image?: (number | null) | Media;
        mobileImage?: (number | null) | Media;
        imageAlt?: string | null;
        variant?: ('image' | 'split' | 'compact') | null;
        theme?: ('brand' | 'light' | 'dark') | null;
        href?: string | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promoBanner';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        layout?: ('steps' | 'cards') | null;
        steps?:
          | {
              icon?: ('search' | 'inspection' | 'financing' | 'delivery' | 'shield') | null;
              label?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustSteps';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        layout?: ('carousel' | 'grid') | null;
        items?:
          | {
              quote?: string | null;
              author?: string | null;
              role?: string | null;
              city?: string | null;
              rating?: number | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        layout?: ('featured' | 'grid') | null;
        videos?:
          | {
              title?: string | null;
              description?: string | null;
              videoUrl?: string | null;
              thumbnail?: (number | null) | Media;
              duration?: string | null;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoTips';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'brands';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        showMap?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'agencies';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        media?: (number | null) | Media;
        layout?: ('mediaLeft' | 'mediaRight') | null;
        link: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaText';
      }
    | {
        heading: string;
        body?: string | null;
        primaryLink: {
          label: string;
          href: string;
        };
        secondaryLink: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  firstName: string;
  lastName?: string | null;
  email?: string | null;
  phone?: string | null;
  city?: string | null;
  agency?: (number | null) | Dealership;
  vehicleLabel?: string | null;
  whatsappNumber?: string | null;
  whatsappOpenedAt?: string | null;
  sourcePage?: string | null;
  sourceSection?: string | null;
  leadSource?: ('whatsapp_vehicle_form' | 'contact_form' | 'phone_click') | null;
  source?:
    | ('website_form' | 'whatsapp' | 'whatsapp_vehicle_form' | 'contact_form' | 'phone_click' | 'phone' | 'walk_in')
    | null;
  vehicle?: (number | null) | Vehicle;
  message?: string | null;
  stage?:
    | ('new' | 'whatsapp_opened' | 'contacted' | 'appointment_set' | 'in_progress' | 'closed_won' | 'closed_lost')
    | null;
  assignedTo?: (number | null) | User;
  contactedBy?: (number | null) | User;
  contactedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  eventType:
    | 'page_view'
    | 'vehicle_view'
    | 'vehicle_click'
    | 'whatsapp_form_open'
    | 'whatsapp_form_submit'
    | 'whatsapp_open'
    | 'collection_view'
    | 'filter_used'
    | 'cta_click'
    | 'page_duration';
  pagePath: string;
  pageTitle?: string | null;
  vehicle?: (number | null) | Vehicle;
  vehicleLabel?: string | null;
  targetLabel?: string | null;
  agency?: (number | null) | Dealership;
  city?: string | null;
  brand?: string | null;
  condition?: string | null;
  collectionId?: (number | null) | VehicleCollection;
  leadId?: (number | null) | Lead;
  sourceSection?: string | null;
  durationSeconds?: number | null;
  sessionId?: string | null;
  visitorId?: string | null;
  deviceType?: ('mobile' | 'tablet' | 'desktop') | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'vehicle-tags';
        value: number | VehicleTag;
      } | null)
    | ({
        relationTo: 'vehicle-collections';
        value: number | VehicleCollection;
      } | null)
    | ({
        relationTo: 'import-jobs';
        value: number | ImportJob;
      } | null)
    | ({
        relationTo: 'vehicle-media-assets';
        value: number | VehicleMediaAsset;
      } | null)
    | ({
        relationTo: 'vehicle-image-searches';
        value: number | VehicleImageSearch;
      } | null)
    | ({
        relationTo: 'workshop-jobs';
        value: number | WorkshopJob;
      } | null)
    | ({
        relationTo: 'image-templates';
        value: number | ImageTemplate;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'dealerships';
        value: number | Dealership;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  uuid?: T;
  slug?: T;
  brand?: T;
  modelFamily?: T;
  model?: T;
  trim?: T;
  year?: T;
  exteriorColor?: T;
  interiorColor?: T;
  vehicleType?: T;
  segment?: T;
  motorType?: T;
  stockId?: T;
  condition?: T;
  dealership?: T;
  city?: T;
  mileage?: T;
  bodyType?: T;
  transmission?: T;
  fuel?: T;
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  tags?: T;
  featured?: T;
  price?: T;
  inventoryStatus?: T;
  publishStatus?: T;
  allowFallbackRouting?: T;
  imageStatus?: T;
  specStatus?: T;
  completenessScore?: T;
  publishedAt?: T;
  lastPublishedBy?: T;
  lastReviewedAt?: T;
  lastReviewedBy?: T;
  reviewNotes?: T;
  sourceId?: T;
  sourceImportId?: T;
  sourceDealerName?: T;
  imageUrl?: T;
  imagePath?: T;
  imageFilename?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        tipo?: T;
        motor?: T;
        potencia?: T;
        transmision?: T;
        combustible?: T;
        traccion?: T;
        cylinders?: T;
        seats?: T;
        doors?: T;
        lengthMm?: T;
        widthMm?: T;
        heightMm?: T;
        wheelbaseMm?: T;
        maxTrunkCapacityL?: T;
        torqueNm?: T;
        fuelTankCapacityL?: T;
      };
  sourceMeta?:
    | T
    | {
        specSource?: T;
        externalMakeId?: T;
        externalModelId?: T;
        externalGenerationId?: T;
        externalTrimId?: T;
        lastSpecSyncAt?: T;
      };
  customFields?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  landing?:
    | T
    | {
        imageText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        highlightList?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  templateOverrides?:
    | T
    | {
        gallery?: T;
        purchaseCard?: T;
        quickSpecs?: T;
        description?: T;
        features?: T;
        similarVehicles?: T;
        mobileCta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-tags_select".
 */
export interface VehicleTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  label?: T;
  description?: T;
  type?: T;
  color?: T;
  isVisible?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-collections_select".
 */
export interface VehicleCollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  collectionType?: T;
  manualVehicles?: T;
  rules?:
    | T
    | {
        condition?: T;
        brand?: T;
        city?: T;
        dealership?: T;
        bodyType?: T;
        segment?: T;
        vehicleType?: T;
        fuel?: T;
        transmission?: T;
        tags?: T;
        inventoryStatus?: T;
        publishStatus?: T;
      };
  sort?: T;
  limit?: T;
  isVisible?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-jobs_select".
 */
export interface ImportJobsSelect<T extends boolean = true> {
  fileName?: T;
  fileType?: T;
  status?: T;
  rowCount?: T;
  createdCount?: T;
  updatedCount?: T;
  skippedCount?: T;
  reviewCount?: T;
  errorCount?: T;
  mapping?: T;
  summary?: T;
  errors?:
    | T
    | {
        row?: T;
        message?: T;
        id?: T;
      };
  createdVehicleIds?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-media-assets_select".
 */
export interface VehicleMediaAssetsSelect<T extends boolean = true> {
  title?: T;
  vehicle?: T;
  media?: T;
  sourceType?: T;
  sourceUrl?: T;
  sourceProvider?: T;
  matchKey?: T;
  make?: T;
  model?: T;
  year?: T;
  trim?: T;
  exteriorColor?: T;
  approvalStatus?: T;
  matchConfidence?: T;
  exteriorColorMatched?: T;
  rightsStatus?: T;
  usage?: T;
  notes?: T;
  createdBy?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-image-searches_select".
 */
export interface VehicleImageSearchesSelect<T extends boolean = true> {
  provider?: T;
  matchKey?: T;
  query?: T;
  candidates?: T;
  fetchedAt?: T;
  expiresAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-jobs_select".
 */
export interface WorkshopJobsSelect<T extends boolean = true> {
  title?: T;
  jobType?: T;
  linkedVehicle?: T;
  inputImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  promptPreset?: T;
  aspectRatio?: T;
  prompt?: T;
  styleTemplate?: T;
  styleName?: T;
  stylePrompt?: T;
  messages?:
    | T
    | {
        role?: T;
        content?: T;
        turnId?: T;
        createdAt?: T;
        id?: T;
      };
  vehicleContext?:
    | T
    | {
        brand?: T;
        model?: T;
        year?: T;
        color?: T;
      };
  styleReferenceUrl?: T;
  outputs?:
    | T
    | {
        image?: T;
        url?: T;
        turnId?: T;
        selected?: T;
        id?: T;
      };
  approvedOutput?: T;
  saveDestination?: T;
  status?: T;
  error?: T;
  createdBy?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-templates_select".
 */
export interface ImageTemplatesSelect<T extends boolean = true> {
  name?: T;
  preset?: T;
  prompt?: T;
  referenceImage?: T;
  description?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isVisible?: T;
  showInNavigation?: T;
  navLabel?: T;
  navParent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              media?: T;
              videoUrl?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoStrip?:
          | T
          | {
              items?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuredVehicles?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              limit?: T;
              source?: T;
              city?: T;
              brand?: T;
              bodyType?: T;
              display?:
                | T
                | {
                    showPrice?: T;
                    showMileage?: T;
                    showCity?: T;
                    showSpecs?: T;
                  };
              vehicles?: T;
              id?: T;
              blockName?: T;
            };
        inventoryCollection?:
          | T
          | {
              collection?: T;
              heading?: T;
              body?: T;
              layout?: T;
              limit?: T;
              display?:
                | T
                | {
                    showPrice?: T;
                    showMileage?: T;
                    showCity?: T;
                    showTags?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        inventorySearch?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              media?: T;
              limit?: T;
              city?: T;
              brand?: T;
              bodyType?: T;
              id?: T;
              blockName?: T;
            };
        cityInventory?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              layout?: T;
              limit?: T;
              cities?:
                | T
                | {
                    city?: T;
                    label?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        promoBanner?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              mobileImage?: T;
              imageAlt?: T;
              variant?: T;
              theme?: T;
              href?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        trustSteps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              layout?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              layout?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    city?: T;
                    rating?: T;
                    image?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        videoTips?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              layout?: T;
              videos?:
                | T
                | {
                    title?: T;
                    description?: T;
                    videoUrl?: T;
                    thumbnail?: T;
                    duration?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        brands?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        agencies?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              media?: T;
              layout?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  city?: T;
  agency?: T;
  vehicleLabel?: T;
  whatsappNumber?: T;
  whatsappOpenedAt?: T;
  sourcePage?: T;
  sourceSection?: T;
  leadSource?: T;
  source?: T;
  vehicle?: T;
  message?: T;
  stage?: T;
  assignedTo?: T;
  contactedBy?: T;
  contactedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  eventType?: T;
  pagePath?: T;
  pageTitle?: T;
  vehicle?: T;
  vehicleLabel?: T;
  targetLabel?: T;
  agency?: T;
  city?: T;
  brand?: T;
  condition?: T;
  collectionId?: T;
  leadId?: T;
  sourceSection?: T;
  durationSeconds?: T;
  sessionId?: T;
  visitorId?: T;
  deviceType?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealerships_select".
 */
export interface DealershipsSelect<T extends boolean = true> {
  brandName?: T;
  displayName?: T;
  city?: T;
  state?: T;
  address?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  hours?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  defaultForCity?: T;
  salesRepName?: T;
  internalNotes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  general?: {
    siteName?: string | null;
    companyName?: string | null;
    slogan?: string | null;
    logo?: (number | null) | Media;
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    address?: string | null;
    socialLinks?: {
      facebook?: string | null;
      instagram?: string | null;
      whatsappUrl?: string | null;
    };
  };
  navigation?: {
    mainLinks?:
      | {
          type?: ('page' | 'collection' | 'brand' | 'inventory' | 'custom') | null;
          label: string;
          href: string;
          children?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    footerLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  home?: {
    sections?:
      | (
          | {
              eyebrow?: string | null;
              heading: string;
              body?: string | null;
              media?: (number | null) | Media;
              videoUrl?: string | null;
              primaryLink: {
                label: string;
                href: string;
              };
              secondaryLink: {
                label: string;
                href: string;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              items?:
                | {
                    image: number | Media;
                    alt?: string | null;
                    href?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'promoStrip';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              limit?: number | null;
              source?: ('latestUsed' | 'manual' | 'city' | 'brand' | 'bodyType') | null;
              city?: string | null;
              brand?: string | null;
              bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
              display?: {
                showPrice?: boolean | null;
                showMileage?: boolean | null;
                showCity?: boolean | null;
                showSpecs?: boolean | null;
              };
              vehicles?: (number | Vehicle)[] | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'featuredVehicles';
            }
          | {
              collection: number | VehicleCollection;
              heading?: string | null;
              body?: string | null;
              layout?: ('grid' | 'carousel' | 'featuredSplit') | null;
              limit?: number | null;
              display?: {
                showPrice?: boolean | null;
                showMileage?: boolean | null;
                showCity?: boolean | null;
                showTags?: boolean | null;
              };
              ctaLabel?: string | null;
              ctaHref?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'inventoryCollection';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              media?: (number | null) | Media;
              limit?: number | null;
              city?: string | null;
              brand?: string | null;
              bodyType?: ('' | 'sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'inventorySearch';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              layout?: ('cards' | 'compact' | 'map') | null;
              limit?: number | null;
              cities?:
                | {
                    city?: string | null;
                    label?: string | null;
                    href?: string | null;
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              ctaLabel?: string | null;
              ctaHref?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'cityInventory';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              image?: (number | null) | Media;
              mobileImage?: (number | null) | Media;
              imageAlt?: string | null;
              variant?: ('image' | 'split' | 'compact') | null;
              theme?: ('brand' | 'light' | 'dark') | null;
              href?: string | null;
              ctaLabel?: string | null;
              ctaHref?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'promoBanner';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              layout?: ('steps' | 'cards') | null;
              steps?:
                | {
                    icon?: ('search' | 'inspection' | 'financing' | 'delivery' | 'shield') | null;
                    label?: string | null;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'trustSteps';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              layout?: ('carousel' | 'grid') | null;
              items?:
                | {
                    quote?: string | null;
                    author?: string | null;
                    role?: string | null;
                    city?: string | null;
                    rating?: number | null;
                    image?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              ctaLabel?: string | null;
              ctaHref?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'testimonials';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              layout?: ('featured' | 'grid') | null;
              videos?:
                | {
                    title?: string | null;
                    description?: string | null;
                    videoUrl?: string | null;
                    thumbnail?: (number | null) | Media;
                    duration?: string | null;
                    id?: string | null;
                  }[]
                | null;
              ctaLabel?: string | null;
              ctaHref?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'videoTips';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'brands';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              showMap?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'agencies';
            }
          | {
              eyebrow?: string | null;
              heading: string;
              body?: string | null;
              media?: (number | null) | Media;
              layout?: ('mediaLeft' | 'mediaRight') | null;
              link: {
                label: string;
                href: string;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'mediaText';
            }
          | {
              heading: string;
              body?: string | null;
              primaryLink: {
                label: string;
                href: string;
              };
              secondaryLink: {
                label: string;
                href: string;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'cta';
            }
        )[]
      | null;
  };
  templates?: {
    seminuevos?: {
      title?: string | null;
      intro?: string | null;
      heroImage?: (number | null) | Media;
      showLocationPrompt?: boolean | null;
    };
    vehicleDetail?: {
      showGallery?: boolean | null;
      showPurchaseCard?: boolean | null;
      showQuickSpecs?: boolean | null;
      showDescription?: boolean | null;
      showFeatures?: boolean | null;
      showSimilarVehicles?: boolean | null;
      showMobileCta?: boolean | null;
      ctaHeading?: string | null;
      ctaBody?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        companyName?: T;
        slogan?: T;
        logo?: T;
        phone?: T;
        whatsapp?: T;
        email?: T;
        address?: T;
        socialLinks?:
          | T
          | {
              facebook?: T;
              instagram?: T;
              whatsappUrl?: T;
            };
      };
  navigation?:
    | T
    | {
        mainLinks?:
          | T
          | {
              type?: T;
              label?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        footerLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  home?:
    | T
    | {
        sections?:
          | T
          | {
              hero?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    media?: T;
                    videoUrl?: T;
                    primaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    secondaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              promoStrip?:
                | T
                | {
                    items?:
                      | T
                      | {
                          image?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              featuredVehicles?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    limit?: T;
                    source?: T;
                    city?: T;
                    brand?: T;
                    bodyType?: T;
                    display?:
                      | T
                      | {
                          showPrice?: T;
                          showMileage?: T;
                          showCity?: T;
                          showSpecs?: T;
                        };
                    vehicles?: T;
                    id?: T;
                    blockName?: T;
                  };
              inventoryCollection?:
                | T
                | {
                    collection?: T;
                    heading?: T;
                    body?: T;
                    layout?: T;
                    limit?: T;
                    display?:
                      | T
                      | {
                          showPrice?: T;
                          showMileage?: T;
                          showCity?: T;
                          showTags?: T;
                        };
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                    blockName?: T;
                  };
              inventorySearch?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    media?: T;
                    limit?: T;
                    city?: T;
                    brand?: T;
                    bodyType?: T;
                    id?: T;
                    blockName?: T;
                  };
              cityInventory?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    layout?: T;
                    limit?: T;
                    cities?:
                      | T
                      | {
                          city?: T;
                          label?: T;
                          href?: T;
                          image?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                    blockName?: T;
                  };
              promoBanner?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    image?: T;
                    mobileImage?: T;
                    imageAlt?: T;
                    variant?: T;
                    theme?: T;
                    href?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                    blockName?: T;
                  };
              trustSteps?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    layout?: T;
                    steps?:
                      | T
                      | {
                          icon?: T;
                          label?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              testimonials?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    layout?: T;
                    items?:
                      | T
                      | {
                          quote?: T;
                          author?: T;
                          role?: T;
                          city?: T;
                          rating?: T;
                          image?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                    blockName?: T;
                  };
              videoTips?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    layout?: T;
                    videos?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          videoUrl?: T;
                          thumbnail?: T;
                          duration?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                    blockName?: T;
                  };
              brands?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              agencies?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    showMap?: T;
                    id?: T;
                    blockName?: T;
                  };
              mediaText?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    media?: T;
                    layout?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              cta?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    primaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    secondaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  templates?:
    | T
    | {
        seminuevos?:
          | T
          | {
              title?: T;
              intro?: T;
              heroImage?: T;
              showLocationPrompt?: T;
            };
        vehicleDetail?:
          | T
          | {
              showGallery?: T;
              showPurchaseCard?: T;
              showQuickSpecs?: T;
              showDescription?: T;
              showFeatures?: T;
              showSimilarVehicles?: T;
              showMobileCta?: T;
              ctaHeading?: T;
              ctaBody?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations-dashboard_widget".
 */
export interface OperationsDashboardWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-dashboard_widget".
 */
export interface AnalyticsDashboardWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}