/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  text,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_vehicles_blocks_image_text_image_position = pgEnum(
  'enum_vehicles_blocks_image_text_image_position',
  ['left', 'right'],
)
export const enum_vehicles_condition = pgEnum('enum_vehicles_condition', ['new', 'used'])
export const enum_vehicles_body_type = pgEnum('enum_vehicles_body_type', [
  'sedan',
  'suv',
  'pickup',
  'coupe',
  'hatchback',
  'van',
  'other',
])
export const enum_vehicles_transmission = pgEnum('enum_vehicles_transmission', [
  'automatic',
  'manual',
  'cvt',
])
export const enum_vehicles_fuel = pgEnum('enum_vehicles_fuel', [
  'gasoline',
  'diesel',
  'hybrid',
  'electric',
])
export const enum_vehicles_inventory_status = pgEnum('enum_vehicles_inventory_status', [
  'available',
  'reserved',
  'sold',
])
export const enum_vehicles_source_meta_spec_source = pgEnum(
  'enum_vehicles_source_meta_spec_source',
  ['catalog', 'rapidapi', 'manual', 'none'],
)
export const enum_leads_source = pgEnum('enum_leads_source', [
  'website_form',
  'whatsapp',
  'phone',
  'walk_in',
])
export const enum_leads_stage = pgEnum('enum_leads_stage', [
  'new',
  'contacted',
  'in_progress',
  'closed_won',
  'closed_lost',
])
export const enum_pages_blocks_featured_vehicles_source = pgEnum(
  'enum_pages_blocks_featured_vehicles_source',
  ['latestUsed', 'manual', 'city', 'brand', 'bodyType'],
)
export const enum_pages_blocks_featured_vehicles_body_type = pgEnum(
  'enum_pages_blocks_featured_vehicles_body_type',
  ['sedan', 'suv', 'pickup', 'coupe', 'hatchback', 'van', 'other'],
)
export const enum_pages_blocks_inventory_search_body_type = pgEnum(
  'enum_pages_blocks_inventory_search_body_type',
  ['', 'sedan', 'suv', 'pickup', 'coupe', 'hatchback', 'van', 'other'],
)
export const enum_pages_blocks_media_text_layout = pgEnum('enum_pages_blocks_media_text_layout', [
  'mediaLeft',
  'mediaRight',
])
export const enum_analytics_events_event_type = pgEnum('enum_analytics_events_event_type', [
  'page_view',
  'vehicle_view',
  'vehicle_click',
  'cta_click',
  'page_duration',
])
export const enum_analytics_events_device_type = pgEnum('enum_analytics_events_device_type', [
  'mobile',
  'tablet',
  'desktop',
])
export const enum_site_config_blocks_featured_vehicles_source = pgEnum(
  'enum_site_config_blocks_featured_vehicles_source',
  ['latestUsed', 'manual', 'city', 'brand', 'bodyType'],
)
export const enum_site_config_blocks_featured_vehicles_body_type = pgEnum(
  'enum_site_config_blocks_featured_vehicles_body_type',
  ['sedan', 'suv', 'pickup', 'coupe', 'hatchback', 'van', 'other'],
)
export const enum_site_config_blocks_inventory_search_body_type = pgEnum(
  'enum_site_config_blocks_inventory_search_body_type',
  ['', 'sedan', 'suv', 'pickup', 'coupe', 'hatchback', 'van', 'other'],
)
export const enum_site_config_blocks_media_text_layout = pgEnum(
  'enum_site_config_blocks_media_text_layout',
  ['mediaLeft', 'mediaRight'],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const vehicles_badges = pgTable(
  'vehicles_badges',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
  },
  (columns) => [
    index('vehicles_badges_order_idx').on(columns._order),
    index('vehicles_badges_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_badges_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_gallery = pgTable(
  'vehicles_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    alt: varchar('alt'),
  },
  (columns) => [
    index('vehicles_gallery_order_idx').on(columns._order),
    index('vehicles_gallery_parent_id_idx').on(columns._parentID),
    index('vehicles_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_features = pgTable(
  'vehicles_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    feature: varchar('feature').notNull(),
  },
  (columns) => [
    index('vehicles_features_order_idx').on(columns._order),
    index('vehicles_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_custom_fields = pgTable(
  'vehicles_custom_fields',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    value: varchar('value').notNull(),
  },
  (columns) => [
    index('vehicles_custom_fields_order_idx').on(columns._order),
    index('vehicles_custom_fields_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_custom_fields_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_image_text = pgTable(
  'vehicles_blocks_image_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow'),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    imagePosition: enum_vehicles_blocks_image_text_image_position('image_position').default('left'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('vehicles_blocks_image_text_order_idx').on(columns._order),
    index('vehicles_blocks_image_text_parent_id_idx').on(columns._parentID),
    index('vehicles_blocks_image_text_path_idx').on(columns._path),
    index('vehicles_blocks_image_text_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_blocks_image_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_gallery_images = pgTable(
  'vehicles_blocks_gallery_images',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    alt: varchar('alt'),
  },
  (columns) => [
    index('vehicles_blocks_gallery_images_order_idx').on(columns._order),
    index('vehicles_blocks_gallery_images_parent_id_idx').on(columns._parentID),
    index('vehicles_blocks_gallery_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles_blocks_gallery.id],
      name: 'vehicles_blocks_gallery_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_gallery = pgTable(
  'vehicles_blocks_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('vehicles_blocks_gallery_order_idx').on(columns._order),
    index('vehicles_blocks_gallery_parent_id_idx').on(columns._parentID),
    index('vehicles_blocks_gallery_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_blocks_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_highlight_list_items = pgTable(
  'vehicles_blocks_highlight_list_items',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    description: varchar('description'),
  },
  (columns) => [
    index('vehicles_blocks_highlight_list_items_order_idx').on(columns._order),
    index('vehicles_blocks_highlight_list_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles_blocks_highlight_list.id],
      name: 'vehicles_blocks_highlight_list_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_highlight_list = pgTable(
  'vehicles_blocks_highlight_list',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('vehicles_blocks_highlight_list_order_idx').on(columns._order),
    index('vehicles_blocks_highlight_list_parent_id_idx').on(columns._parentID),
    index('vehicles_blocks_highlight_list_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_blocks_highlight_list_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_feature_grid_items = pgTable(
  'vehicles_blocks_feature_grid_items',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    feature: varchar('feature').notNull(),
  },
  (columns) => [
    index('vehicles_blocks_feature_grid_items_order_idx').on(columns._order),
    index('vehicles_blocks_feature_grid_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles_blocks_feature_grid.id],
      name: 'vehicles_blocks_feature_grid_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_feature_grid = pgTable(
  'vehicles_blocks_feature_grid',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('vehicles_blocks_feature_grid_order_idx').on(columns._order),
    index('vehicles_blocks_feature_grid_parent_id_idx').on(columns._parentID),
    index('vehicles_blocks_feature_grid_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_blocks_feature_grid_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles_blocks_cta = pgTable(
  'vehicles_blocks_cta',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    buttonLabel: varchar('button_label').default('Consultar por WhatsApp'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('vehicles_blocks_cta_order_idx').on(columns._order),
    index('vehicles_blocks_cta_parent_id_idx').on(columns._parentID),
    index('vehicles_blocks_cta_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [vehicles.id],
      name: 'vehicles_blocks_cta_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const vehicles = pgTable(
  'vehicles',
  {
    id: serial('id').primaryKey(),
    uuid: varchar('uuid'),
    slug: varchar('slug').notNull(),
    brand: varchar('brand').notNull(),
    model: varchar('model').notNull(),
    year: numeric('year', { mode: 'number' }).notNull(),
    stockId: varchar('stock_id'),
    condition: enum_vehicles_condition('condition').notNull().default('new'),
    dealership: integer('dealership_id')
      .notNull()
      .references(() => dealerships.id, {
        onDelete: 'set null',
      }),
    city: varchar('city'),
    mileage: numeric('mileage', { mode: 'number' }),
    bodyType: enum_vehicles_body_type('body_type'),
    transmission: enum_vehicles_transmission('transmission'),
    fuel: enum_vehicles_fuel('fuel'),
    price: varchar('price').notNull(),
    inventoryStatus: enum_vehicles_inventory_status('inventory_status')
      .notNull()
      .default('available'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    specs_tipo: varchar('specs_tipo'),
    specs_motor: varchar('specs_motor'),
    specs_potencia: varchar('specs_potencia'),
    specs_transmision: varchar('specs_transmision'),
    specs_combustible: varchar('specs_combustible'),
    specs_traccion: varchar('specs_traccion'),
    specs_cylinders: varchar('specs_cylinders'),
    specs_seats: varchar('specs_seats'),
    specs_doors: varchar('specs_doors'),
    specs_lengthMm: varchar('specs_length_mm'),
    specs_widthMm: varchar('specs_width_mm'),
    specs_heightMm: varchar('specs_height_mm'),
    specs_wheelbaseMm: varchar('specs_wheelbase_mm'),
    specs_maxTrunkCapacityL: varchar('specs_max_trunk_capacity_l'),
    specs_torqueNm: varchar('specs_torque_nm'),
    specs_fuelTankCapacityL: varchar('specs_fuel_tank_capacity_l'),
    sourceMeta_specSource:
      enum_vehicles_source_meta_spec_source('source_meta_spec_source').default('manual'),
    sourceMeta_externalMakeId: varchar('source_meta_external_make_id'),
    sourceMeta_externalModelId: varchar('source_meta_external_model_id'),
    sourceMeta_externalGenerationId: varchar('source_meta_external_generation_id'),
    sourceMeta_externalTrimId: varchar('source_meta_external_trim_id'),
    sourceMeta_lastSpecSyncAt: timestamp('source_meta_last_spec_sync_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('vehicles_uuid_idx').on(columns.uuid),
    uniqueIndex('vehicles_slug_idx').on(columns.slug),
    index('vehicles_dealership_idx').on(columns.dealership),
    index('vehicles_image_idx').on(columns.image),
    index('vehicles_updated_at_idx').on(columns.updatedAt),
    index('vehicles_created_at_idx').on(columns.createdAt),
  ],
)

export const dealerships = pgTable(
  'dealerships',
  {
    id: serial('id').primaryKey(),
    brandName: varchar('brand_name').notNull(),
    displayName: varchar('display_name').notNull(),
    city: varchar('city').notNull(),
    phone: varchar('phone'),
    whatsapp: varchar('whatsapp'),
    coordinates_lat: numeric('coordinates_lat', { mode: 'number' }),
    coordinates_lng: numeric('coordinates_lng', { mode: 'number' }),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('dealerships_updated_at_idx').on(columns.updatedAt),
    index('dealerships_created_at_idx').on(columns.createdAt),
  ],
)

export const leads = pgTable(
  'leads',
  {
    id: serial('id').primaryKey(),
    firstName: varchar('first_name').notNull(),
    lastName: varchar('last_name'),
    email: varchar('email'),
    phone: varchar('phone').notNull(),
    source: enum_leads_source('source').default('website_form'),
    vehicle: integer('vehicle_id').references(() => vehicles.id, {
      onDelete: 'set null',
    }),
    message: varchar('message'),
    stage: enum_leads_stage('stage').default('new'),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('leads_vehicle_idx').on(columns.vehicle),
    index('leads_updated_at_idx').on(columns.updatedAt),
    index('leads_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_blocks_hero = pgTable(
  'pages_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow'),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    videoUrl: varchar('video_url'),
    primaryLink_label: varchar('primary_link_label').notNull(),
    primaryLink_href: varchar('primary_link_href').notNull(),
    secondaryLink_label: varchar('secondary_link_label').notNull(),
    secondaryLink_href: varchar('secondary_link_href').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_hero_order_idx').on(columns._order),
    index('pages_blocks_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_hero_path_idx').on(columns._path),
    index('pages_blocks_hero_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_promo_strip_items = pgTable(
  'pages_blocks_promo_strip_items',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    alt: varchar('alt'),
    href: varchar('href'),
  },
  (columns) => [
    index('pages_blocks_promo_strip_items_order_idx').on(columns._order),
    index('pages_blocks_promo_strip_items_parent_id_idx').on(columns._parentID),
    index('pages_blocks_promo_strip_items_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_promo_strip.id],
      name: 'pages_blocks_promo_strip_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_promo_strip = pgTable(
  'pages_blocks_promo_strip',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_promo_strip_order_idx').on(columns._order),
    index('pages_blocks_promo_strip_parent_id_idx').on(columns._parentID),
    index('pages_blocks_promo_strip_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_promo_strip_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_featured_vehicles = pgTable(
  'pages_blocks_featured_vehicles',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Seminuevos'),
    heading: varchar('heading').default('Vehiculos destacados'),
    body: varchar('body'),
    limit: numeric('limit', { mode: 'number' }).default(6),
    source: enum_pages_blocks_featured_vehicles_source('source').default('latestUsed'),
    city: varchar('city'),
    brand: varchar('brand'),
    bodyType: enum_pages_blocks_featured_vehicles_body_type('body_type'),
    display_showPrice: boolean('display_show_price').default(true),
    display_showMileage: boolean('display_show_mileage').default(true),
    display_showCity: boolean('display_show_city').default(true),
    display_showSpecs: boolean('display_show_specs').default(true),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_featured_vehicles_order_idx').on(columns._order),
    index('pages_blocks_featured_vehicles_parent_id_idx').on(columns._parentID),
    index('pages_blocks_featured_vehicles_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_featured_vehicles_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_inventory_search = pgTable(
  'pages_blocks_inventory_search',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Inventario'),
    heading: varchar('heading').default('Encuentra tu seminuevo'),
    body: varchar('body'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    limit: numeric('limit', { mode: 'number' }).default(6),
    city: varchar('city'),
    brand: varchar('brand'),
    bodyType: enum_pages_blocks_inventory_search_body_type('body_type'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_inventory_search_order_idx').on(columns._order),
    index('pages_blocks_inventory_search_parent_id_idx').on(columns._parentID),
    index('pages_blocks_inventory_search_path_idx').on(columns._path),
    index('pages_blocks_inventory_search_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_inventory_search_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_brands = pgTable(
  'pages_blocks_brands',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Marcas'),
    heading: varchar('heading').default('Las mejores marcas, en un solo lugar'),
    body: varchar('body'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_brands_order_idx').on(columns._order),
    index('pages_blocks_brands_parent_id_idx').on(columns._parentID),
    index('pages_blocks_brands_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_brands_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_agencies = pgTable(
  'pages_blocks_agencies',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Encuentranos'),
    heading: varchar('heading').default('Nuestras agencias'),
    body: varchar('body'),
    showMap: boolean('show_map').default(true),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_agencies_order_idx').on(columns._order),
    index('pages_blocks_agencies_parent_id_idx').on(columns._parentID),
    index('pages_blocks_agencies_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_agencies_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_media_text = pgTable(
  'pages_blocks_media_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow'),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    layout: enum_pages_blocks_media_text_layout('layout').default('mediaLeft'),
    link_label: varchar('link_label').notNull(),
    link_href: varchar('link_href').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_media_text_order_idx').on(columns._order),
    index('pages_blocks_media_text_parent_id_idx').on(columns._parentID),
    index('pages_blocks_media_text_path_idx').on(columns._path),
    index('pages_blocks_media_text_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_media_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_cta = pgTable(
  'pages_blocks_cta',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    primaryLink_label: varchar('primary_link_label').notNull(),
    primaryLink_href: varchar('primary_link_href').notNull(),
    secondaryLink_label: varchar('secondary_link_label').notNull(),
    secondaryLink_href: varchar('secondary_link_href').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_cta_order_idx').on(columns._order),
    index('pages_blocks_cta_parent_id_idx').on(columns._parentID),
    index('pages_blocks_cta_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_cta_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    isVisible: boolean('is_visible').default(true),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    seo_image: integer('seo_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_seo_seo_image_idx').on(columns.seo_image),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    vehiclesID: integer('vehicles_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_vehicles_id_idx').on(columns.vehiclesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['vehiclesID']],
      foreignColumns: [vehicles.id],
      name: 'pages_rels_vehicles_fk',
    }).onDelete('cascade'),
  ],
)

export const analytics_events = pgTable(
  'analytics_events',
  {
    id: serial('id').primaryKey(),
    eventType: enum_analytics_events_event_type('event_type').notNull(),
    pagePath: varchar('page_path').notNull(),
    pageTitle: varchar('page_title'),
    vehicle: integer('vehicle_id').references(() => vehicles.id, {
      onDelete: 'set null',
    }),
    vehicleLabel: varchar('vehicle_label'),
    targetLabel: varchar('target_label'),
    durationSeconds: numeric('duration_seconds', { mode: 'number' }),
    sessionId: varchar('session_id'),
    visitorId: varchar('visitor_id'),
    deviceType: enum_analytics_events_device_type('device_type'),
    referrer: varchar('referrer'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('analytics_events_vehicle_idx').on(columns.vehicle),
    index('analytics_events_updated_at_idx').on(columns.updatedAt),
    index('analytics_events_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    vehiclesID: integer('vehicles_id'),
    dealershipsID: integer('dealerships_id'),
    leadsID: integer('leads_id'),
    pagesID: integer('pages_id'),
    'analytics-eventsID': integer('analytics_events_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_vehicles_id_idx').on(columns.vehiclesID),
    index('payload_locked_documents_rels_dealerships_id_idx').on(columns.dealershipsID),
    index('payload_locked_documents_rels_leads_id_idx').on(columns.leadsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_analytics_events_id_idx').on(
      columns['analytics-eventsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['vehiclesID']],
      foreignColumns: [vehicles.id],
      name: 'payload_locked_documents_rels_vehicles_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['dealershipsID']],
      foreignColumns: [dealerships.id],
      name: 'payload_locked_documents_rels_dealerships_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['leadsID']],
      foreignColumns: [leads.id],
      name: 'payload_locked_documents_rels_leads_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['analytics-eventsID']],
      foreignColumns: [analytics_events.id],
      name: 'payload_locked_documents_rels_analytics_events_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site_config_navigation_main_links_children = pgTable(
  'site_config_navigation_main_links_children',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('site_config_navigation_main_links_children_order_idx').on(columns._order),
    index('site_config_navigation_main_links_children_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config_navigation_main_links.id],
      name: 'site_config_navigation_main_links_children_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_navigation_main_links = pgTable(
  'site_config_navigation_main_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('site_config_navigation_main_links_order_idx').on(columns._order),
    index('site_config_navigation_main_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_navigation_main_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_hero = pgTable(
  'site_config_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow'),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    videoUrl: varchar('video_url'),
    primaryLink_label: varchar('primary_link_label').notNull(),
    primaryLink_href: varchar('primary_link_href').notNull(),
    secondaryLink_label: varchar('secondary_link_label').notNull(),
    secondaryLink_href: varchar('secondary_link_href').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_hero_order_idx').on(columns._order),
    index('site_config_blocks_hero_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_hero_path_idx').on(columns._path),
    index('site_config_blocks_hero_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_promo_strip_items = pgTable(
  'site_config_blocks_promo_strip_items',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    alt: varchar('alt'),
    href: varchar('href'),
  },
  (columns) => [
    index('site_config_blocks_promo_strip_items_order_idx').on(columns._order),
    index('site_config_blocks_promo_strip_items_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_promo_strip_items_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config_blocks_promo_strip.id],
      name: 'site_config_blocks_promo_strip_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_promo_strip = pgTable(
  'site_config_blocks_promo_strip',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_promo_strip_order_idx').on(columns._order),
    index('site_config_blocks_promo_strip_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_promo_strip_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_promo_strip_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_featured_vehicles = pgTable(
  'site_config_blocks_featured_vehicles',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Seminuevos'),
    heading: varchar('heading').default('Vehiculos destacados'),
    body: varchar('body'),
    limit: numeric('limit', { mode: 'number' }).default(6),
    source: enum_site_config_blocks_featured_vehicles_source('source').default('latestUsed'),
    city: varchar('city'),
    brand: varchar('brand'),
    bodyType: enum_site_config_blocks_featured_vehicles_body_type('body_type'),
    display_showPrice: boolean('display_show_price').default(true),
    display_showMileage: boolean('display_show_mileage').default(true),
    display_showCity: boolean('display_show_city').default(true),
    display_showSpecs: boolean('display_show_specs').default(true),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_featured_vehicles_order_idx').on(columns._order),
    index('site_config_blocks_featured_vehicles_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_featured_vehicles_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_featured_vehicles_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_inventory_search = pgTable(
  'site_config_blocks_inventory_search',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Inventario'),
    heading: varchar('heading').default('Encuentra tu seminuevo'),
    body: varchar('body'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    limit: numeric('limit', { mode: 'number' }).default(6),
    city: varchar('city'),
    brand: varchar('brand'),
    bodyType: enum_site_config_blocks_inventory_search_body_type('body_type'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_inventory_search_order_idx').on(columns._order),
    index('site_config_blocks_inventory_search_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_inventory_search_path_idx').on(columns._path),
    index('site_config_blocks_inventory_search_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_inventory_search_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_brands = pgTable(
  'site_config_blocks_brands',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Marcas'),
    heading: varchar('heading').default('Las mejores marcas, en un solo lugar'),
    body: varchar('body'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_brands_order_idx').on(columns._order),
    index('site_config_blocks_brands_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_brands_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_brands_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_agencies = pgTable(
  'site_config_blocks_agencies',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('Encuentranos'),
    heading: varchar('heading').default('Nuestras agencias'),
    body: varchar('body'),
    showMap: boolean('show_map').default(true),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_agencies_order_idx').on(columns._order),
    index('site_config_blocks_agencies_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_agencies_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_agencies_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_media_text = pgTable(
  'site_config_blocks_media_text',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow'),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    layout: enum_site_config_blocks_media_text_layout('layout').default('mediaLeft'),
    link_label: varchar('link_label').notNull(),
    link_href: varchar('link_href').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_media_text_order_idx').on(columns._order),
    index('site_config_blocks_media_text_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_media_text_path_idx').on(columns._path),
    index('site_config_blocks_media_text_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_media_text_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config_blocks_cta = pgTable(
  'site_config_blocks_cta',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading').notNull(),
    body: varchar('body'),
    primaryLink_label: varchar('primary_link_label').notNull(),
    primaryLink_href: varchar('primary_link_href').notNull(),
    secondaryLink_label: varchar('secondary_link_label').notNull(),
    secondaryLink_href: varchar('secondary_link_href').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('site_config_blocks_cta_order_idx').on(columns._order),
    index('site_config_blocks_cta_parent_id_idx').on(columns._parentID),
    index('site_config_blocks_cta_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_config.id],
      name: 'site_config_blocks_cta_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const site_config = pgTable(
  'site_config',
  {
    id: serial('id').primaryKey(),
    general_siteName: varchar('general_site_name').default('GB Automotriz'),
    general_companyName: varchar('general_company_name'),
    general_slogan: varchar('general_slogan'),
    general_logo: integer('general_logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    general_phone: varchar('general_phone'),
    general_whatsapp: varchar('general_whatsapp'),
    general_email: varchar('general_email'),
    general_address: varchar('general_address'),
    general_socialLinks_facebook: varchar('general_social_links_facebook'),
    general_socialLinks_instagram: varchar('general_social_links_instagram'),
    general_socialLinks_whatsappUrl: varchar('general_social_links_whatsapp_url'),
    navigation_cta_label: varchar('navigation_cta_label'),
    navigation_cta_href: varchar('navigation_cta_href'),
    templates_seminuevos_title: varchar('templates_seminuevos_title').default('Autos seminuevos'),
    templates_seminuevos_intro: varchar('templates_seminuevos_intro'),
    templates_seminuevos_heroImage: integer('templates_seminuevos_hero_image_id').references(
      () => media.id,
      {
        onDelete: 'set null',
      },
    ),
    templates_seminuevos_showLocationPrompt: boolean(
      'templates_seminuevos_show_location_prompt',
    ).default(true),
    templates_vehicleDetail_showSimilarVehicles: boolean(
      'templates_vehicle_detail_show_similar_vehicles',
    ).default(true),
    templates_vehicleDetail_ctaHeading: varchar('templates_vehicle_detail_cta_heading').default(
      'Aparta este vehiculo',
    ),
    templates_vehicleDetail_ctaBody: varchar('templates_vehicle_detail_cta_body'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('site_config_general_general_logo_idx').on(columns.general_logo),
    index('site_config_templates_seminuevos_templates_seminuevos_he_idx').on(
      columns.templates_seminuevos_heroImage,
    ),
  ],
)

export const site_config_rels = pgTable(
  'site_config_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    vehiclesID: integer('vehicles_id'),
  },
  (columns) => [
    index('site_config_rels_order_idx').on(columns.order),
    index('site_config_rels_parent_idx').on(columns.parent),
    index('site_config_rels_path_idx').on(columns.path),
    index('site_config_rels_vehicles_id_idx').on(columns.vehiclesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [site_config.id],
      name: 'site_config_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['vehiclesID']],
      foreignColumns: [vehicles.id],
      name: 'site_config_rels_vehicles_fk',
    }).onDelete('cascade'),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_vehicles_badges = relations(vehicles_badges, ({ one }) => ({
  _parentID: one(vehicles, {
    fields: [vehicles_badges._parentID],
    references: [vehicles.id],
    relationName: 'badges',
  }),
}))
export const relations_vehicles_gallery = relations(vehicles_gallery, ({ one }) => ({
  _parentID: one(vehicles, {
    fields: [vehicles_gallery._parentID],
    references: [vehicles.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [vehicles_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_vehicles_features = relations(vehicles_features, ({ one }) => ({
  _parentID: one(vehicles, {
    fields: [vehicles_features._parentID],
    references: [vehicles.id],
    relationName: 'features',
  }),
}))
export const relations_vehicles_custom_fields = relations(vehicles_custom_fields, ({ one }) => ({
  _parentID: one(vehicles, {
    fields: [vehicles_custom_fields._parentID],
    references: [vehicles.id],
    relationName: 'customFields',
  }),
}))
export const relations_vehicles_blocks_image_text = relations(
  vehicles_blocks_image_text,
  ({ one }) => ({
    _parentID: one(vehicles, {
      fields: [vehicles_blocks_image_text._parentID],
      references: [vehicles.id],
      relationName: '_blocks_imageText',
    }),
    image: one(media, {
      fields: [vehicles_blocks_image_text.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_vehicles_blocks_gallery_images = relations(
  vehicles_blocks_gallery_images,
  ({ one }) => ({
    _parentID: one(vehicles_blocks_gallery, {
      fields: [vehicles_blocks_gallery_images._parentID],
      references: [vehicles_blocks_gallery.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [vehicles_blocks_gallery_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_vehicles_blocks_gallery = relations(
  vehicles_blocks_gallery,
  ({ one, many }) => ({
    _parentID: one(vehicles, {
      fields: [vehicles_blocks_gallery._parentID],
      references: [vehicles.id],
      relationName: '_blocks_gallery',
    }),
    images: many(vehicles_blocks_gallery_images, {
      relationName: 'images',
    }),
  }),
)
export const relations_vehicles_blocks_highlight_list_items = relations(
  vehicles_blocks_highlight_list_items,
  ({ one }) => ({
    _parentID: one(vehicles_blocks_highlight_list, {
      fields: [vehicles_blocks_highlight_list_items._parentID],
      references: [vehicles_blocks_highlight_list.id],
      relationName: 'items',
    }),
  }),
)
export const relations_vehicles_blocks_highlight_list = relations(
  vehicles_blocks_highlight_list,
  ({ one, many }) => ({
    _parentID: one(vehicles, {
      fields: [vehicles_blocks_highlight_list._parentID],
      references: [vehicles.id],
      relationName: '_blocks_highlightList',
    }),
    items: many(vehicles_blocks_highlight_list_items, {
      relationName: 'items',
    }),
  }),
)
export const relations_vehicles_blocks_feature_grid_items = relations(
  vehicles_blocks_feature_grid_items,
  ({ one }) => ({
    _parentID: one(vehicles_blocks_feature_grid, {
      fields: [vehicles_blocks_feature_grid_items._parentID],
      references: [vehicles_blocks_feature_grid.id],
      relationName: 'items',
    }),
  }),
)
export const relations_vehicles_blocks_feature_grid = relations(
  vehicles_blocks_feature_grid,
  ({ one, many }) => ({
    _parentID: one(vehicles, {
      fields: [vehicles_blocks_feature_grid._parentID],
      references: [vehicles.id],
      relationName: '_blocks_featureGrid',
    }),
    items: many(vehicles_blocks_feature_grid_items, {
      relationName: 'items',
    }),
  }),
)
export const relations_vehicles_blocks_cta = relations(vehicles_blocks_cta, ({ one }) => ({
  _parentID: one(vehicles, {
    fields: [vehicles_blocks_cta._parentID],
    references: [vehicles.id],
    relationName: '_blocks_cta',
  }),
}))
export const relations_vehicles = relations(vehicles, ({ one, many }) => ({
  dealership: one(dealerships, {
    fields: [vehicles.dealership],
    references: [dealerships.id],
    relationName: 'dealership',
  }),
  badges: many(vehicles_badges, {
    relationName: 'badges',
  }),
  image: one(media, {
    fields: [vehicles.image],
    references: [media.id],
    relationName: 'image',
  }),
  gallery: many(vehicles_gallery, {
    relationName: 'gallery',
  }),
  features: many(vehicles_features, {
    relationName: 'features',
  }),
  customFields: many(vehicles_custom_fields, {
    relationName: 'customFields',
  }),
  _blocks_imageText: many(vehicles_blocks_image_text, {
    relationName: '_blocks_imageText',
  }),
  _blocks_gallery: many(vehicles_blocks_gallery, {
    relationName: '_blocks_gallery',
  }),
  _blocks_highlightList: many(vehicles_blocks_highlight_list, {
    relationName: '_blocks_highlightList',
  }),
  _blocks_featureGrid: many(vehicles_blocks_feature_grid, {
    relationName: '_blocks_featureGrid',
  }),
  _blocks_cta: many(vehicles_blocks_cta, {
    relationName: '_blocks_cta',
  }),
}))
export const relations_dealerships = relations(dealerships, () => ({}))
export const relations_leads = relations(leads, ({ one }) => ({
  vehicle: one(vehicles, {
    fields: [leads.vehicle],
    references: [vehicles.id],
    relationName: 'vehicle',
  }),
}))
export const relations_pages_blocks_hero = relations(pages_blocks_hero, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_hero._parentID],
    references: [pages.id],
    relationName: '_blocks_hero',
  }),
  media: one(media, {
    fields: [pages_blocks_hero.media],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_pages_blocks_promo_strip_items = relations(
  pages_blocks_promo_strip_items,
  ({ one }) => ({
    _parentID: one(pages_blocks_promo_strip, {
      fields: [pages_blocks_promo_strip_items._parentID],
      references: [pages_blocks_promo_strip.id],
      relationName: 'items',
    }),
    image: one(media, {
      fields: [pages_blocks_promo_strip_items.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_pages_blocks_promo_strip = relations(
  pages_blocks_promo_strip,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_promo_strip._parentID],
      references: [pages.id],
      relationName: '_blocks_promoStrip',
    }),
    items: many(pages_blocks_promo_strip_items, {
      relationName: 'items',
    }),
  }),
)
export const relations_pages_blocks_featured_vehicles = relations(
  pages_blocks_featured_vehicles,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_featured_vehicles._parentID],
      references: [pages.id],
      relationName: '_blocks_featuredVehicles',
    }),
  }),
)
export const relations_pages_blocks_inventory_search = relations(
  pages_blocks_inventory_search,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_inventory_search._parentID],
      references: [pages.id],
      relationName: '_blocks_inventorySearch',
    }),
    media: one(media, {
      fields: [pages_blocks_inventory_search.media],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_pages_blocks_brands = relations(pages_blocks_brands, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_brands._parentID],
    references: [pages.id],
    relationName: '_blocks_brands',
  }),
}))
export const relations_pages_blocks_agencies = relations(pages_blocks_agencies, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_agencies._parentID],
    references: [pages.id],
    relationName: '_blocks_agencies',
  }),
}))
export const relations_pages_blocks_media_text = relations(pages_blocks_media_text, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_media_text._parentID],
    references: [pages.id],
    relationName: '_blocks_mediaText',
  }),
  media: one(media, {
    fields: [pages_blocks_media_text.media],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_pages_blocks_cta = relations(pages_blocks_cta, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_cta._parentID],
    references: [pages.id],
    relationName: '_blocks_cta',
  }),
}))
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  vehiclesID: one(vehicles, {
    fields: [pages_rels.vehiclesID],
    references: [vehicles.id],
    relationName: 'vehicles',
  }),
}))
export const relations_pages = relations(pages, ({ one, many }) => ({
  seo_image: one(media, {
    fields: [pages.seo_image],
    references: [media.id],
    relationName: 'seo_image',
  }),
  _blocks_hero: many(pages_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_promoStrip: many(pages_blocks_promo_strip, {
    relationName: '_blocks_promoStrip',
  }),
  _blocks_featuredVehicles: many(pages_blocks_featured_vehicles, {
    relationName: '_blocks_featuredVehicles',
  }),
  _blocks_inventorySearch: many(pages_blocks_inventory_search, {
    relationName: '_blocks_inventorySearch',
  }),
  _blocks_brands: many(pages_blocks_brands, {
    relationName: '_blocks_brands',
  }),
  _blocks_agencies: many(pages_blocks_agencies, {
    relationName: '_blocks_agencies',
  }),
  _blocks_mediaText: many(pages_blocks_media_text, {
    relationName: '_blocks_mediaText',
  }),
  _blocks_cta: many(pages_blocks_cta, {
    relationName: '_blocks_cta',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations_analytics_events = relations(analytics_events, ({ one }) => ({
  vehicle: one(vehicles, {
    fields: [analytics_events.vehicle],
    references: [vehicles.id],
    relationName: 'vehicle',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    vehiclesID: one(vehicles, {
      fields: [payload_locked_documents_rels.vehiclesID],
      references: [vehicles.id],
      relationName: 'vehicles',
    }),
    dealershipsID: one(dealerships, {
      fields: [payload_locked_documents_rels.dealershipsID],
      references: [dealerships.id],
      relationName: 'dealerships',
    }),
    leadsID: one(leads, {
      fields: [payload_locked_documents_rels.leadsID],
      references: [leads.id],
      relationName: 'leads',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    'analytics-eventsID': one(analytics_events, {
      fields: [payload_locked_documents_rels['analytics-eventsID']],
      references: [analytics_events.id],
      relationName: 'analytics-events',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site_config_navigation_main_links_children = relations(
  site_config_navigation_main_links_children,
  ({ one }) => ({
    _parentID: one(site_config_navigation_main_links, {
      fields: [site_config_navigation_main_links_children._parentID],
      references: [site_config_navigation_main_links.id],
      relationName: 'children',
    }),
  }),
)
export const relations_site_config_navigation_main_links = relations(
  site_config_navigation_main_links,
  ({ one, many }) => ({
    _parentID: one(site_config, {
      fields: [site_config_navigation_main_links._parentID],
      references: [site_config.id],
      relationName: 'navigation_mainLinks',
    }),
    children: many(site_config_navigation_main_links_children, {
      relationName: 'children',
    }),
  }),
)
export const relations_site_config_blocks_hero = relations(site_config_blocks_hero, ({ one }) => ({
  _parentID: one(site_config, {
    fields: [site_config_blocks_hero._parentID],
    references: [site_config.id],
    relationName: '_blocks_hero',
  }),
  media: one(media, {
    fields: [site_config_blocks_hero.media],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_site_config_blocks_promo_strip_items = relations(
  site_config_blocks_promo_strip_items,
  ({ one }) => ({
    _parentID: one(site_config_blocks_promo_strip, {
      fields: [site_config_blocks_promo_strip_items._parentID],
      references: [site_config_blocks_promo_strip.id],
      relationName: 'items',
    }),
    image: one(media, {
      fields: [site_config_blocks_promo_strip_items.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_site_config_blocks_promo_strip = relations(
  site_config_blocks_promo_strip,
  ({ one, many }) => ({
    _parentID: one(site_config, {
      fields: [site_config_blocks_promo_strip._parentID],
      references: [site_config.id],
      relationName: '_blocks_promoStrip',
    }),
    items: many(site_config_blocks_promo_strip_items, {
      relationName: 'items',
    }),
  }),
)
export const relations_site_config_blocks_featured_vehicles = relations(
  site_config_blocks_featured_vehicles,
  ({ one }) => ({
    _parentID: one(site_config, {
      fields: [site_config_blocks_featured_vehicles._parentID],
      references: [site_config.id],
      relationName: '_blocks_featuredVehicles',
    }),
  }),
)
export const relations_site_config_blocks_inventory_search = relations(
  site_config_blocks_inventory_search,
  ({ one }) => ({
    _parentID: one(site_config, {
      fields: [site_config_blocks_inventory_search._parentID],
      references: [site_config.id],
      relationName: '_blocks_inventorySearch',
    }),
    media: one(media, {
      fields: [site_config_blocks_inventory_search.media],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_site_config_blocks_brands = relations(
  site_config_blocks_brands,
  ({ one }) => ({
    _parentID: one(site_config, {
      fields: [site_config_blocks_brands._parentID],
      references: [site_config.id],
      relationName: '_blocks_brands',
    }),
  }),
)
export const relations_site_config_blocks_agencies = relations(
  site_config_blocks_agencies,
  ({ one }) => ({
    _parentID: one(site_config, {
      fields: [site_config_blocks_agencies._parentID],
      references: [site_config.id],
      relationName: '_blocks_agencies',
    }),
  }),
)
export const relations_site_config_blocks_media_text = relations(
  site_config_blocks_media_text,
  ({ one }) => ({
    _parentID: one(site_config, {
      fields: [site_config_blocks_media_text._parentID],
      references: [site_config.id],
      relationName: '_blocks_mediaText',
    }),
    media: one(media, {
      fields: [site_config_blocks_media_text.media],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_site_config_blocks_cta = relations(site_config_blocks_cta, ({ one }) => ({
  _parentID: one(site_config, {
    fields: [site_config_blocks_cta._parentID],
    references: [site_config.id],
    relationName: '_blocks_cta',
  }),
}))
export const relations_site_config_rels = relations(site_config_rels, ({ one }) => ({
  parent: one(site_config, {
    fields: [site_config_rels.parent],
    references: [site_config.id],
    relationName: '_rels',
  }),
  vehiclesID: one(vehicles, {
    fields: [site_config_rels.vehiclesID],
    references: [vehicles.id],
    relationName: 'vehicles',
  }),
}))
export const relations_site_config = relations(site_config, ({ one, many }) => ({
  general_logo: one(media, {
    fields: [site_config.general_logo],
    references: [media.id],
    relationName: 'general_logo',
  }),
  navigation_mainLinks: many(site_config_navigation_main_links, {
    relationName: 'navigation_mainLinks',
  }),
  _blocks_hero: many(site_config_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_promoStrip: many(site_config_blocks_promo_strip, {
    relationName: '_blocks_promoStrip',
  }),
  _blocks_featuredVehicles: many(site_config_blocks_featured_vehicles, {
    relationName: '_blocks_featuredVehicles',
  }),
  _blocks_inventorySearch: many(site_config_blocks_inventory_search, {
    relationName: '_blocks_inventorySearch',
  }),
  _blocks_brands: many(site_config_blocks_brands, {
    relationName: '_blocks_brands',
  }),
  _blocks_agencies: many(site_config_blocks_agencies, {
    relationName: '_blocks_agencies',
  }),
  _blocks_mediaText: many(site_config_blocks_media_text, {
    relationName: '_blocks_mediaText',
  }),
  _blocks_cta: many(site_config_blocks_cta, {
    relationName: '_blocks_cta',
  }),
  templates_seminuevos_heroImage: one(media, {
    fields: [site_config.templates_seminuevos_heroImage],
    references: [media.id],
    relationName: 'templates_seminuevos_heroImage',
  }),
  _rels: many(site_config_rels, {
    relationName: '_rels',
  }),
}))

type DatabaseSchema = {
  enum_vehicles_blocks_image_text_image_position: typeof enum_vehicles_blocks_image_text_image_position
  enum_vehicles_condition: typeof enum_vehicles_condition
  enum_vehicles_body_type: typeof enum_vehicles_body_type
  enum_vehicles_transmission: typeof enum_vehicles_transmission
  enum_vehicles_fuel: typeof enum_vehicles_fuel
  enum_vehicles_inventory_status: typeof enum_vehicles_inventory_status
  enum_vehicles_source_meta_spec_source: typeof enum_vehicles_source_meta_spec_source
  enum_leads_source: typeof enum_leads_source
  enum_leads_stage: typeof enum_leads_stage
  enum_pages_blocks_featured_vehicles_source: typeof enum_pages_blocks_featured_vehicles_source
  enum_pages_blocks_featured_vehicles_body_type: typeof enum_pages_blocks_featured_vehicles_body_type
  enum_pages_blocks_inventory_search_body_type: typeof enum_pages_blocks_inventory_search_body_type
  enum_pages_blocks_media_text_layout: typeof enum_pages_blocks_media_text_layout
  enum_analytics_events_event_type: typeof enum_analytics_events_event_type
  enum_analytics_events_device_type: typeof enum_analytics_events_device_type
  enum_site_config_blocks_featured_vehicles_source: typeof enum_site_config_blocks_featured_vehicles_source
  enum_site_config_blocks_featured_vehicles_body_type: typeof enum_site_config_blocks_featured_vehicles_body_type
  enum_site_config_blocks_inventory_search_body_type: typeof enum_site_config_blocks_inventory_search_body_type
  enum_site_config_blocks_media_text_layout: typeof enum_site_config_blocks_media_text_layout
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  vehicles_badges: typeof vehicles_badges
  vehicles_gallery: typeof vehicles_gallery
  vehicles_features: typeof vehicles_features
  vehicles_custom_fields: typeof vehicles_custom_fields
  vehicles_blocks_image_text: typeof vehicles_blocks_image_text
  vehicles_blocks_gallery_images: typeof vehicles_blocks_gallery_images
  vehicles_blocks_gallery: typeof vehicles_blocks_gallery
  vehicles_blocks_highlight_list_items: typeof vehicles_blocks_highlight_list_items
  vehicles_blocks_highlight_list: typeof vehicles_blocks_highlight_list
  vehicles_blocks_feature_grid_items: typeof vehicles_blocks_feature_grid_items
  vehicles_blocks_feature_grid: typeof vehicles_blocks_feature_grid
  vehicles_blocks_cta: typeof vehicles_blocks_cta
  vehicles: typeof vehicles
  dealerships: typeof dealerships
  leads: typeof leads
  pages_blocks_hero: typeof pages_blocks_hero
  pages_blocks_promo_strip_items: typeof pages_blocks_promo_strip_items
  pages_blocks_promo_strip: typeof pages_blocks_promo_strip
  pages_blocks_featured_vehicles: typeof pages_blocks_featured_vehicles
  pages_blocks_inventory_search: typeof pages_blocks_inventory_search
  pages_blocks_brands: typeof pages_blocks_brands
  pages_blocks_agencies: typeof pages_blocks_agencies
  pages_blocks_media_text: typeof pages_blocks_media_text
  pages_blocks_cta: typeof pages_blocks_cta
  pages: typeof pages
  pages_rels: typeof pages_rels
  analytics_events: typeof analytics_events
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_config_navigation_main_links_children: typeof site_config_navigation_main_links_children
  site_config_navigation_main_links: typeof site_config_navigation_main_links
  site_config_blocks_hero: typeof site_config_blocks_hero
  site_config_blocks_promo_strip_items: typeof site_config_blocks_promo_strip_items
  site_config_blocks_promo_strip: typeof site_config_blocks_promo_strip
  site_config_blocks_featured_vehicles: typeof site_config_blocks_featured_vehicles
  site_config_blocks_inventory_search: typeof site_config_blocks_inventory_search
  site_config_blocks_brands: typeof site_config_blocks_brands
  site_config_blocks_agencies: typeof site_config_blocks_agencies
  site_config_blocks_media_text: typeof site_config_blocks_media_text
  site_config_blocks_cta: typeof site_config_blocks_cta
  site_config: typeof site_config
  site_config_rels: typeof site_config_rels
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_vehicles_badges: typeof relations_vehicles_badges
  relations_vehicles_gallery: typeof relations_vehicles_gallery
  relations_vehicles_features: typeof relations_vehicles_features
  relations_vehicles_custom_fields: typeof relations_vehicles_custom_fields
  relations_vehicles_blocks_image_text: typeof relations_vehicles_blocks_image_text
  relations_vehicles_blocks_gallery_images: typeof relations_vehicles_blocks_gallery_images
  relations_vehicles_blocks_gallery: typeof relations_vehicles_blocks_gallery
  relations_vehicles_blocks_highlight_list_items: typeof relations_vehicles_blocks_highlight_list_items
  relations_vehicles_blocks_highlight_list: typeof relations_vehicles_blocks_highlight_list
  relations_vehicles_blocks_feature_grid_items: typeof relations_vehicles_blocks_feature_grid_items
  relations_vehicles_blocks_feature_grid: typeof relations_vehicles_blocks_feature_grid
  relations_vehicles_blocks_cta: typeof relations_vehicles_blocks_cta
  relations_vehicles: typeof relations_vehicles
  relations_dealerships: typeof relations_dealerships
  relations_leads: typeof relations_leads
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero
  relations_pages_blocks_promo_strip_items: typeof relations_pages_blocks_promo_strip_items
  relations_pages_blocks_promo_strip: typeof relations_pages_blocks_promo_strip
  relations_pages_blocks_featured_vehicles: typeof relations_pages_blocks_featured_vehicles
  relations_pages_blocks_inventory_search: typeof relations_pages_blocks_inventory_search
  relations_pages_blocks_brands: typeof relations_pages_blocks_brands
  relations_pages_blocks_agencies: typeof relations_pages_blocks_agencies
  relations_pages_blocks_media_text: typeof relations_pages_blocks_media_text
  relations_pages_blocks_cta: typeof relations_pages_blocks_cta
  relations_pages_rels: typeof relations_pages_rels
  relations_pages: typeof relations_pages
  relations_analytics_events: typeof relations_analytics_events
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_config_navigation_main_links_children: typeof relations_site_config_navigation_main_links_children
  relations_site_config_navigation_main_links: typeof relations_site_config_navigation_main_links
  relations_site_config_blocks_hero: typeof relations_site_config_blocks_hero
  relations_site_config_blocks_promo_strip_items: typeof relations_site_config_blocks_promo_strip_items
  relations_site_config_blocks_promo_strip: typeof relations_site_config_blocks_promo_strip
  relations_site_config_blocks_featured_vehicles: typeof relations_site_config_blocks_featured_vehicles
  relations_site_config_blocks_inventory_search: typeof relations_site_config_blocks_inventory_search
  relations_site_config_blocks_brands: typeof relations_site_config_blocks_brands
  relations_site_config_blocks_agencies: typeof relations_site_config_blocks_agencies
  relations_site_config_blocks_media_text: typeof relations_site_config_blocks_media_text
  relations_site_config_blocks_cta: typeof relations_site_config_blocks_cta
  relations_site_config_rels: typeof relations_site_config_rels
  relations_site_config: typeof relations_site_config
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
