/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    vehicles: Vehicle;
    dealerships: Dealership;
    leads: Lead;
    pages: Page;
    'analytics-events': AnalyticsEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    dealerships: DealershipsSelect<false> | DealershipsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: null;
  widgets: {
    'analytics-dashboard': AnalyticsDashboardWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  uuid?: string | null;
  /**
   * Se genera al guardar con marca, modelo, año y UUID del vehículo.
   */
  slug: string;
  brand: string;
  model: string;
  year: number;
  /**
   * Referencia visible para ventas y WhatsApp. Si se deja vacio se usara el UUID corto.
   */
  stockId?: string | null;
  condition: 'new' | 'used';
  /**
   * Define a que agencia pertenece esta unidad y a que WhatsApp se enviaran los leads.
   */
  dealership: number | Dealership;
  /**
   * Opcional. Si se deja vacia, la pagina usara la ciudad de la agencia seleccionada.
   */
  city?: string | null;
  mileage?: number | null;
  bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
  transmission?: ('automatic' | 'manual' | 'cvt') | null;
  fuel?: ('gasoline' | 'diesel' | 'hybrid' | 'electric') | null;
  /**
   * Crea etiquetas como Un dueno, Garantia, Factura agencia, Promo o Recien llegado.
   */
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Escribe un número o rango. Se guardará automáticamente como MXN.
   */
  price: string;
  inventoryStatus: 'available' | 'reserved' | 'sold';
  image?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  specs?: {
    tipo?: string | null;
    motor?: string | null;
    potencia?: string | null;
    transmision?: string | null;
    combustible?: string | null;
    traccion?: string | null;
    cylinders?: string | null;
    seats?: string | null;
    doors?: string | null;
    lengthMm?: string | null;
    widthMm?: string | null;
    heightMm?: string | null;
    wheelbaseMm?: string | null;
    maxTrunkCapacityL?: string | null;
    torqueNm?: string | null;
    fuelTankCapacityL?: string | null;
  };
  /**
   * Datos tecnicos normalizados desde catalogo interno o RapidAPI.
   */
  sourceMeta?: {
    specSource?: ('catalog' | 'rapidapi' | 'manual' | 'none') | null;
    externalMakeId?: string | null;
    externalModelId?: string | null;
    externalGenerationId?: string | null;
    externalTrimId?: string | null;
    lastSpecSyncAt?: string | null;
  };
  /**
   * Datos importados desde CSV que no pertenecen al esquema principal.
   */
  customFields?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Agrega secciones simples debajo de la pagina del vehiculo: imagen y texto, galerias, beneficios o CTA.
   */
  landing?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            body?: string | null;
            items?:
              | {
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlightList';
          }
        | {
            heading: string;
            items?:
              | {
                  feature: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealerships".
 */
export interface Dealership {
  id: number;
  brandName: string;
  displayName: string;
  city: string;
  phone?: string | null;
  whatsapp?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  firstName: string;
  lastName?: string | null;
  email?: string | null;
  phone: string;
  source?: ('website_form' | 'whatsapp' | 'phone' | 'walk_in') | null;
  vehicle?: (number | null) | Vehicle;
  message?: string | null;
  stage?: ('new' | 'contacted' | 'in_progress' | 'closed_won' | 'closed_lost') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * No uses rutas reservadas como cars, seminuevos, marcas o api.
   */
  slug: string;
  isVisible?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  sections: (
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        media?: (number | null) | Media;
        videoUrl?: string | null;
        primaryLink: {
          label: string;
          href: string;
        };
        secondaryLink: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        items?:
          | {
              image: number | Media;
              alt?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promoStrip';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        limit?: number | null;
        source?: ('latestUsed' | 'manual' | 'city' | 'brand' | 'bodyType') | null;
        city?: string | null;
        brand?: string | null;
        bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
        display?: {
          showPrice?: boolean | null;
          showMileage?: boolean | null;
          showCity?: boolean | null;
          showSpecs?: boolean | null;
        };
        vehicles?: (number | Vehicle)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuredVehicles';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        media?: (number | null) | Media;
        limit?: number | null;
        city?: string | null;
        brand?: string | null;
        bodyType?: ('' | 'sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'inventorySearch';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'brands';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        showMap?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'agencies';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        media?: (number | null) | Media;
        layout?: ('mediaLeft' | 'mediaRight') | null;
        link: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaText';
      }
    | {
        heading: string;
        body?: string | null;
        primaryLink: {
          label: string;
          href: string;
        };
        secondaryLink: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  eventType: 'page_view' | 'vehicle_view' | 'vehicle_click' | 'cta_click' | 'page_duration';
  pagePath: string;
  pageTitle?: string | null;
  vehicle?: (number | null) | Vehicle;
  vehicleLabel?: string | null;
  targetLabel?: string | null;
  durationSeconds?: number | null;
  sessionId?: string | null;
  visitorId?: string | null;
  deviceType?: ('mobile' | 'tablet' | 'desktop') | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'dealerships';
        value: number | Dealership;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  uuid?: T;
  slug?: T;
  brand?: T;
  model?: T;
  year?: T;
  stockId?: T;
  condition?: T;
  dealership?: T;
  city?: T;
  mileage?: T;
  bodyType?: T;
  transmission?: T;
  fuel?: T;
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  price?: T;
  inventoryStatus?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        tipo?: T;
        motor?: T;
        potencia?: T;
        transmision?: T;
        combustible?: T;
        traccion?: T;
        cylinders?: T;
        seats?: T;
        doors?: T;
        lengthMm?: T;
        widthMm?: T;
        heightMm?: T;
        wheelbaseMm?: T;
        maxTrunkCapacityL?: T;
        torqueNm?: T;
        fuelTankCapacityL?: T;
      };
  sourceMeta?:
    | T
    | {
        specSource?: T;
        externalMakeId?: T;
        externalModelId?: T;
        externalGenerationId?: T;
        externalTrimId?: T;
        lastSpecSyncAt?: T;
      };
  customFields?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  landing?:
    | T
    | {
        imageText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        highlightList?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealerships_select".
 */
export interface DealershipsSelect<T extends boolean = true> {
  brandName?: T;
  displayName?: T;
  city?: T;
  phone?: T;
  whatsapp?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  source?: T;
  vehicle?: T;
  message?: T;
  stage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isVisible?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              media?: T;
              videoUrl?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoStrip?:
          | T
          | {
              items?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuredVehicles?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              limit?: T;
              source?: T;
              city?: T;
              brand?: T;
              bodyType?: T;
              display?:
                | T
                | {
                    showPrice?: T;
                    showMileage?: T;
                    showCity?: T;
                    showSpecs?: T;
                  };
              vehicles?: T;
              id?: T;
              blockName?: T;
            };
        inventorySearch?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              media?: T;
              limit?: T;
              city?: T;
              brand?: T;
              bodyType?: T;
              id?: T;
              blockName?: T;
            };
        brands?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        agencies?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              media?: T;
              layout?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  eventType?: T;
  pagePath?: T;
  pageTitle?: T;
  vehicle?: T;
  vehicleLabel?: T;
  targetLabel?: T;
  durationSeconds?: T;
  sessionId?: T;
  visitorId?: T;
  deviceType?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  general?: {
    siteName?: string | null;
    companyName?: string | null;
    slogan?: string | null;
    logo?: (number | null) | Media;
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    address?: string | null;
    socialLinks?: {
      facebook?: string | null;
      instagram?: string | null;
      whatsappUrl?: string | null;
    };
  };
  navigation?: {
    mainLinks?:
      | {
          label: string;
          href: string;
          children?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  home?: {
    sections?:
      | (
          | {
              eyebrow?: string | null;
              heading: string;
              body?: string | null;
              media?: (number | null) | Media;
              videoUrl?: string | null;
              primaryLink: {
                label: string;
                href: string;
              };
              secondaryLink: {
                label: string;
                href: string;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              items?:
                | {
                    image: number | Media;
                    alt?: string | null;
                    href?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'promoStrip';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              limit?: number | null;
              source?: ('latestUsed' | 'manual' | 'city' | 'brand' | 'bodyType') | null;
              city?: string | null;
              brand?: string | null;
              bodyType?: ('sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
              display?: {
                showPrice?: boolean | null;
                showMileage?: boolean | null;
                showCity?: boolean | null;
                showSpecs?: boolean | null;
              };
              vehicles?: (number | Vehicle)[] | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'featuredVehicles';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              media?: (number | null) | Media;
              limit?: number | null;
              city?: string | null;
              brand?: string | null;
              bodyType?: ('' | 'sedan' | 'suv' | 'pickup' | 'coupe' | 'hatchback' | 'van' | 'other') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'inventorySearch';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'brands';
            }
          | {
              eyebrow?: string | null;
              heading?: string | null;
              body?: string | null;
              showMap?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'agencies';
            }
          | {
              eyebrow?: string | null;
              heading: string;
              body?: string | null;
              media?: (number | null) | Media;
              layout?: ('mediaLeft' | 'mediaRight') | null;
              link: {
                label: string;
                href: string;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'mediaText';
            }
          | {
              heading: string;
              body?: string | null;
              primaryLink: {
                label: string;
                href: string;
              };
              secondaryLink: {
                label: string;
                href: string;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'cta';
            }
        )[]
      | null;
  };
  templates?: {
    seminuevos?: {
      title?: string | null;
      intro?: string | null;
      heroImage?: (number | null) | Media;
      showLocationPrompt?: boolean | null;
    };
    vehicleDetail?: {
      showSimilarVehicles?: boolean | null;
      ctaHeading?: string | null;
      ctaBody?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        companyName?: T;
        slogan?: T;
        logo?: T;
        phone?: T;
        whatsapp?: T;
        email?: T;
        address?: T;
        socialLinks?:
          | T
          | {
              facebook?: T;
              instagram?: T;
              whatsappUrl?: T;
            };
      };
  navigation?:
    | T
    | {
        mainLinks?:
          | T
          | {
              label?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  home?:
    | T
    | {
        sections?:
          | T
          | {
              hero?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    media?: T;
                    videoUrl?: T;
                    primaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    secondaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              promoStrip?:
                | T
                | {
                    items?:
                      | T
                      | {
                          image?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              featuredVehicles?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    limit?: T;
                    source?: T;
                    city?: T;
                    brand?: T;
                    bodyType?: T;
                    display?:
                      | T
                      | {
                          showPrice?: T;
                          showMileage?: T;
                          showCity?: T;
                          showSpecs?: T;
                        };
                    vehicles?: T;
                    id?: T;
                    blockName?: T;
                  };
              inventorySearch?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    media?: T;
                    limit?: T;
                    city?: T;
                    brand?: T;
                    bodyType?: T;
                    id?: T;
                    blockName?: T;
                  };
              brands?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              agencies?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    showMap?: T;
                    id?: T;
                    blockName?: T;
                  };
              mediaText?:
                | T
                | {
                    eyebrow?: T;
                    heading?: T;
                    body?: T;
                    media?: T;
                    layout?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              cta?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    primaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    secondaryLink?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  templates?:
    | T
    | {
        seminuevos?:
          | T
          | {
              title?: T;
              intro?: T;
              heroImage?: T;
              showLocationPrompt?: T;
            };
        vehicleDetail?:
          | T
          | {
              showSimilarVehicles?: T;
              ctaHeading?: T;
              ctaBody?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-dashboard_widget".
 */
export interface AnalyticsDashboardWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}